name: Python CI/CD Practice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v4

      # Первый раз - просто собираем образ (Build)
      - name: Docker Build
        run: docker build -t myapp .

      # Второй раз - запускаем тесты внутри этого образа
      - name: Docker Run Tests
        run: docker run myapp

      - name: CD процесс (Деплой)
        run: |
          mkdir -p ../staging
          cp -r . ../staging/